-- Insert sample vaccination schedules data
INSERT INTO
    vaccination_schedules (
        student_id,
        student_name,
        student_code,
        vaccine_name,
        scheduled_date_time,
        is_vaccinated,
        parent_consent,
        student_confirmation,
        notes,
        location,
        batch_number,
        created_by,
        created_date,
        updated_date
    )
VALUES (
        1,
        'Nguyễn Văn A',
        'HS001',
        'COVID-19',
        '2024-01-15 08:00:00',
        false,
        'PENDING',
        false,
        'Mũi tiêm COVID-19 lần 1',
        'Phòng y tế trường học',
        'COVID-001',
        'nurse@school.com',
        NOW(),
        NOW()
    ),
    (
        2,
        'Trần Thị B',
        'HS002',
        'Cúm',
        '2024-01-16 09:00:00',
        false,
        'APPROVED',
        false,
        'Vaccine cúm mùa',
        'Phòng y tế trường học',
        'FLU-001',
        'nurse@school.com',
        NOW(),
        NOW()
    ),
    (
        3,
        'Lê Văn C',
        'HS003',
        'Viêm gan B',
        '2024-01-17 10:00:00',
        true,
        'APPROVED',
        true,
        'Mũi tiêm viêm gan B',
        'Phòng y tế trường học',
        'HEP-B-001',
        'nurse@school.com',
        NOW(),
        NOW()
    ),
    (
        4,
        'Phạm Thị D',
        'HS004',
        'Sởi',
        '2024-01-18 11:00:00',
        false,
        'REJECTED',
        false,
        'Vaccine sởi',
        'Phòng y tế trường học',
        'MEASLES-001',
        'nurse@school.com',
        NOW(),
        NOW()
    ),
    (
        5,
        'Hoàng Văn E',
        'HS005',
        'Bạch hầu - Ho gà - Uốn ván',
        '2024-01-19 14:00:00',
        false,
        'PENDING',
        false,
        'Vaccine 5 trong 1',
        'Phòng y tế trường học',
        'DPT-001',
        'nurse@school.com',
        NOW(),
        NOW()
    );